<?php

namespace Data\Repository;

use Data\Entity\Person;
use Doctrine\ORM\EntityRepository;

/**
 * PersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonRepository extends EntityRepository
{
    public function search($filter = null)
    {
        $dql = $this->_em->createQuery('SELECT p FROM '.Person::class.' p WHERE p.name like :name or p.birthDate = :birthDate');
        $dql->setParameter('name','%'.$filter.'%');
        $dql->setParameter('birthDate',$filter);

        return $dql->execute();
    }
}
