<?php

namespace Data\Repository;

use Data\Entity\Product;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function search($filter = null)
    {
        $dql = $this->_em->createQuery('SELECT p FROM '.Product::class.' p 
        WHERE p.name like :name 
            or p.code like :code 
            or p.unitPrice like :unitPrice');


        $dql->setParameter('name','%'.$filter.'%');
        $dql->setParameter('code','%'.$filter.'%');
        $dql->setParameter('unitPrice','%'.$filter.'%');

        return $dql->execute();
    }
}
