<?php

namespace Data\Repository;

use Data\Entity\Sale;
use Data\Entity\SaleItem;
use Doctrine\ORM\EntityRepository;

/**
 * SaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleRepository extends EntityRepository
{

    public function updateTotal(Sale $sale, $flush = true)
    {
        $total = 0;

        foreach ($sale->getItems() as $item)
        {
            if(!($item instanceof SaleItem))
            {
                throw new \UnexpectedValueException('Bad value !');
            }

            $total += $item->getTotal();
        }

        $sale->setTotal($total);
        $this->_em->merge($sale);

        if($flush === true){
            $this->_em->flush();
        }
    }

    public function getNextNumberSequence()
    {
        $sql = $this->_em->getConnection()->getWrappedConnection()->prepare('
            SELECT IFNULL(max(number),1) + 1 AS NUMBER FROM sale;
        ');

        $sql->execute();
        return $sql->fetchAll(\PDO::FETCH_ASSOC)[0]['NUMBER'];
    }

    public function search($filter = null)
    {
        $dql = $this->_em->createQuery('SELECT s FROM '.Sale::class.' s 
            JOIN s.client p
        WHERE p.name like :name 
              or s.date = :date
              or s.total like :total
              or s.number = :number
        ');
        $dql->setParameter('name','%'.$filter.'%');
        $dql->setParameter('date',$filter);
        $dql->setParameter('total','%'.$filter.'%');
        $dql->setParameter('number', $filter);

        return $dql->execute();
    }
}
