<?php

namespace Data\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SaleItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleItemRepository extends EntityRepository
{
}
